### ISSUE TITLE
処理別に関数を作り、実装をする

### ISSUE THREAD

**Issue by TKRD7** [TKRDisFootball/TheTkrdPark#10]
ver0.1.0にて実装予定。
現在は一つの関数の中で複数の処理(削除、完了時の処理、配列データへの登録など)が行われている。
この関数を改良し、それぞれ機能別(表示・登録・削除・更新)に関数を作る。
開発の際、MVCモデルを参考に開発作業を進めていく。

**Comment by TKRD7** [comment]
現状→各機能別に関数を分けることが難しいが、自分の出来る範囲で実装を行った。
今後のアップデートで改良を加えていく必要がある。

**Comment by jinmayamashita** [comment]
MVCでなんか詰まっているところがあれば相談してくださいー！
意外と難しく考える必要はないので 😄 

0.2.0 で実装目指していきましょう！:fire:

**Comment by TKRD7** [comment]
ver0.2.0のコードリファクタリングにおいて、
いくつかの機能を、それぞれの関数に分けて実装することができた。

Issueの問題を解決しましたので、当該Issueはクローズ致します。
