### ISSUE TITLE
公開について

### ISSUE THREAD

**Issue by jinmayamashita** [TKRDisFootball/TheTkrdPark#11]
色々知識が増えましたな！:smile:
せっかくだし、単純な機能が揃ったら
[Github page](https://techacademy.jp/magazine/6445)に公開して見るのはいかがでしょう。:thumbsup:

**Comment by TKRD7** [comment]
はい！ver0.1.0の状態で、Github pageにて公開できるように進めてみます！

**Comment by jinmayamashita** [comment]
頑張って公開まで成功、お疲れ様様でした！:clap:
公開は完了したようでこのIssueはCloseします 🙏
